from Engine.objects import GameObject, Camera
import pygame


class GameManager:
    gameObjects: list[GameObject]
    camera: Camera

    def add_game_object(self, obj: GameObject): ...

    def delete_game_object(self, obj: GameObject): ...

    def get_game_object(self, type_obj: type) -> GameObject: ...

    def get_game_objects(self) -> list[GameObject]: ...

    def draw(self, surface: pygame.Surface): ...
    def update(self): ...
    def change_camera_position(self, position: list[int]): ...
    def change_camera_size(self, size: list[int]): ...
